# -*- coding: utf-8 -*-
"""admin_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aR5Er7c5BRCA5CuyvMjU99d87uMRn-o
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.set_page_config(page_title="Admin Dashboard", layout="wide")
st.title("📊 E-Commerce Survey Admin Dashboard")

# Load responses
try:
    df = pd.read_csv("responses.csv")
    st.success(f"Loaded {len(df)} responses.")
except FileNotFoundError:
    st.error("No survey data found. Please submit some responses first.")
    st.stop()

# Filters
with st.sidebar:
    st.header("🔍 Filters")
    age_filter = st.multiselect("Filter by Age", df['age'].unique())
    gender_filter = st.multiselect("Filter by Gender", df['gender'].unique())

# Apply filters
if age_filter:
    df = df[df['age'].isin(age_filter)]
if gender_filter:
    df = df[df['gender'].isin(gender_filter)]

# Display stats
st.subheader("🧮 Summary Statistics")
st.write(df.describe(include='all'))

# Pie chart: Shopping Frequency
st.subheader("🛍️ Shopping Frequency")
fig1, ax1 = plt.subplots()
df['shop_freq'].value_counts().plot.pie(autopct='%1.1f%%', ax=ax1)
ax1.set_ylabel("")
st.pyplot(fig1)

# Bar chart: Satisfaction
st.subheader("😊 Satisfaction Levels")
st.bar_chart(df['satisfaction'].value_counts().sort_index())

# Net Promoter Score (Q9)
st.subheader("📈 Recommendation (NPS)")
st.bar_chart(df['recommendation'].value_counts().sort_index())

# Optional: Download data
st.subheader("📥 Download Responses")
st.download_button("Download CSV", df.to_csv(index=False), "survey_data.csv")