# -*- coding: utf-8 -*-
"""ecommerce_survey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VhuHx75P5ighfZDywsHKGNSk3rmKn25
"""

streamlit run ecommerce_survey.py