# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYQLtvmAtD3TZs1TcJxUhanIT-ft586Y
"""

import streamlit as st
import pandas as pd

st.title("E-Commerce Survey")

age = st.selectbox("Your Age Group", ["<18", "18-25", "26-35", "36-50", "50+"])
gender = st.selectbox("Gender", ["Male", "Female", "Other"])
frequency = st.radio("How often do you shop online?", ["Daily", "Weekly", "Monthly", "Rarely", "Never"])
satisfaction = st.slider("How satisfied are you with your overall online shopping experience?", 1, 5)

value = st.multiselect("What do you value most in online shopping?",
                       ["Price", "Product Quality", "Delivery Speed", "Return Policy", "Customer Service", "Security"])

trust = st.slider("How much do you trust online payments?", 1, 5)

recommend = st.slider("How likely are you to recommend online shopping to a friend? (0-10)", 0, 10)

feedback = st.text_area("Any suggestions to improve online shopping experience?")

if st.button("Submit"):
    st.success("Thank you for your feedback!")